### ISSUE TITLE
想问下楼主的服务器是用哪里的

### ISSUE THREAD

**Issue by hechuanhua** [tianxiangbing/mobile-select-area#14]
我也想弄一个，但是国外的貌似要国际信用卡才能开，怎么拿到免费的服务器....

**Comment by tianxiangbing** [comment]
什么服务器？github是免费的啊，我的网站www.lovewebgames.com是用的一年60块钱的虚拟空间。 @hechuanhua ，react-cn.com这个是阿里云的免费空间。国外的也很多免费的，但都是短期的，既然免费了还要什么信用卡？chat.lovewebgames.com是挂在国外一个免费的node服务器上的。

**Comment by hechuanhua** [comment]
@tianxiangbing 我想问有没有那种可以自己搭建环境的免费服务器，比如搭建node，mongoDB，Python什么的。。。。。
我看亚马逊貌似有免费的，但是貌似要国际信用卡才能体验1年。。。。

**Comment by tianxiangbing** [comment]
@hechuanhua 你去node中国找下吧，有这块的资源的，我之前就有用。不过不稳定。

**Comment by hechuanhua** [comment]
@tianxiangbing   chat.lovewebgames.com是挂在国外一个免费的node服务器上的

这个是在国外哪个网站，可以发地址给我吗，我也想去弄一个

**Comment by tianxiangbing** [comment]
heroku
