### ISSUE TITLE
请添加webpack支持

### ISSUE THREAD

**Issue by SquallATF** [tianxiangbing/mobile-select-area#15]
问题1 package.config中没有main设置，直接require("mobile-select-area")找不到模块
问题2 dialog的package.config中没有main设置导致 mobile-select-area require("dialog") 找不到模块
问题3 mobile-select-area 中对jquery的引用是require("$")而npm的jquery包需要require("jquery")

**Comment by tianxiangbing** [comment]
恩，已添加npm install mobile-select-area
