### ISSUE TITLE
请问回调函数要怎么使用？？

### ISSUE THREAD

**Issue by me683547** [tianxiangbing/mobile-select-area#19]
请问回调函数要怎么使用？？

**Comment by tianxiangbing** [comment]
@me683547 与其他参数一样传入即可。
selectArea.init({ trigger: '#txt_area3', data: 'data.json', default: 0, callback:function(a,b,c){
}});

callback:function(scroller,text,value)

第一个是容器，第二个是选中后的text值，第三个参数是选中后的id。
并且this指向当前对象。
选中后的回调，默认有填充trigger的value值，以及赋值它后面紧跟着的hidden的value值，以逗号分隔id，空格分隔文字

**Comment by me683547** [comment]
刚才发现不是这个问题了，原来你那份js里面可以直接修改。不过还是谢谢你
