### ISSUE TITLE
怎样使用zepto？

### ISSUE THREAD

**Issue by YangPengFe1** [tianxiangbing/mobile-select-area#20]
首先谢谢作者。
我在使用时的过程中，需要用zepto来，实现三级联动。

然后：

`<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
		<title>新增收货地址</title>
		<link rel="stylesheet" href="../plugins/mobileSelect/mobile-select-area.css" />
	</head>

	<body class="bg-blank">
		
	
		<input type="text" id="txt_area"  placeholder="所在城市" style="padding-left: 0;" />
	
		

//注释以上的线上链接的话就没有问题

		<script src="../plugins/libs/zepto.min.js"></script>
		<script type="text/javascript" src="../plugins/mobileSelect/dialog.js" ></script>
		<script type="text/javascript" src="../plugins/mobileSelect/mobile-select-area.js" ></script>
		
	</body>

</html>`
文件链接顺序大概如图所示，我的需求是基于zepto 实现一个三级联动的选择器。

使用 zepto和本地的文件就会报错。使用JQ 就没有报错。我现在应该怎么做，才能让它用zepto 跑起来。

**Comment by YangPengFe1** [comment]
使用zepto报搓如下。

Uncaught TypeError: $.Deferred is not a function
    at MobileSelectArea.getData (mobile-select-area.js:64)
    at MobileSelectArea.show (mobile-select-area.js:123)
    at HTMLInputElement.<anonymous> (mobile-select-area.js:181)
    at HTMLInputElement.a.proxy (zepto.min.js:2)

**Comment by YangPengFe1** [comment]
使用zepto报错如下。

Uncaught TypeError: $.Deferred is not a function
at MobileSelectArea.getData (mobile-select-area.js:64)
at MobileSelectArea.show (mobile-select-area.js:123)
at HTMLInputElement. (mobile-select-area.js:181)
at HTMLInputElement.a.proxy (zepto.min.js:2)

**Comment by YangPengFe1** [comment]
很着急，希望有人能够回答我的问题。

**Comment by tianxiangbing** [comment]
@ximige 是这样的，只有前面的版本是对zepto有特意做过兼容的，后面的推荐使用jquery，zepto是个按需下载的js库，你这里是Deferred模块没有安装，你也可以使用我的zepto来跑，或者你下载一个较全模块的zepto.又或者你使用https://github.com/tianxiangbing/mobile-select-area/blob/1.0.6/src/mobile-select-area.js  1.x的版本应该都是没有Deferred。
