### ISSUE TITLE
有什么方法可以兼容pc端

### ISSUE THREAD

**Issue by nicolaslh** [tianxiangbing/mobile-select-area#22]
pc端点击不能弹出选择框, 有的浏览器弹出了选项框不能滑动选择

**Comment by nicolaslh** [comment]
有什么方法可以兼容pc端吗

**Comment by tianxiangbing** [comment]
这个是专为手机端写的，pc端访问需要打开调试工具的手机模拟形态，如果你要在pc上用的话，得去兼容touchmove等触控事件改为鼠标事件
