### ISSUE TITLE
不能分级获得数据

### ISSUE THREAD

**Issue by cyqlegend** [tianxiangbing/mobile-select-area#4]
现在似乎还做不到选择完一级数据后通过ajax获得下一级数据。希望能增加

**Comment by tianxiangbing** [comment]
因为从性能上来讲，省市区的信息是不多的，后台完全能够一次把所有的数据返回回来进行缓存处理，基本不会变的，或者生成js文件保存数据，所以在选一级去加载下一级的数据是很不必要资源浪费，而且会超成用户的等待loading，从综合衡量上来说，省市区这种静态数据源的，是没必要分几次请求的。
