### ISSUE TITLE
大神，有bug

### ISSUE THREAD

**Issue by cadleo** [tianxiangbing/mobile-select-area#6]
在部分chrome以及基于chrome的第三方浏览器下选择地址的触摸滚动事件不会触发，问题最先出现在 chrome  47.0.2526.73 m (64-bit)PC版的手机调试工具，后续测了部分第三方浏览器。火狐移动版，ie移动版都能正常使用。但是为什么大神的那些demo在同一个chrome却能运行良好呢？？神奇

新发现，似乎因为amd规范的原因，不能随意更换jquery版本？

**Comment by cadleo** [comment]
发现原因，mask或dialogContainer或dialogContent晚出现一小段时间就不会出问题，算是一个浏览器的bug吧，就是下面这段代码

>   this.mask.show();
>           this.dailogContent.show();
>           this.height = this.settings.height || 'auto' //this.dialogContainer.height();
>           this.width = this.settings.width || 'auto' //this.dialogContainer.width();
>           this.dialogContainer.append(this.dailogContent).show().css({
>               height: this.height,
>               width: this.width
>           });

**Comment by cadleo** [comment]
发现更深层次的原因，应该是css3 animation的bug，把参数animate设为false就没事了，过渡效果可以通过其他方式实现，不搞了，累死了

**Comment by tianxiangbing** [comment]
css3支持不好，已经添加参数
